Repository allthingslinux/tux, pull requests merged in 2024-08, with the labels that each got.

#412 Add slowmode get subcommand
  tux/cogs/moderation/slowmode.py
Labels: category: commands

#444 Add role and emote info commands
  tux/cogs/info/info.py
Labels: category: commands, status: resolved, type: enhancement, priority: low

#443 Add snippet banning and unbanning
  prisma/schema.prisma
  tux/cogs/moderation/cases.py
  tux/cogs/moderation/snippetban.py
  tux/cogs/moderation/snippetunban.py
  tux/cogs/utility/snippets.py
  tux/utils/flags.py
Labels: category: commands, type: feature-request, status: resolved, priority: high

#455 added snippet ban check to editing snippets
  tux/cogs/utility/snippets.py
Labels: category: commands, type: enhancement, priority: medium

#459 make some naming changes, remove an inaccurate docstring
  tux/cogs/misc/run.py
Labels: category: documentation, type: enhancement, priority: low

#446 Add fun fact command
  tux/cogs/fun/fact.py
Labels: category: commands, type: feature-request, status: resolved, priority: low

#470 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: category: documentation, priority: high

#469 add basic image manipulation
  tux/cogs/fun/imgeffect.py
Labels: category: commands, status: work-in-progress, type: enhancement, priority: medium, good first issue

#481 feat: defer processing message instead of reply
  tux/cogs/fun/imgeffect.py
Labels: category: commands, type: feature-request, priority: low, status: needs testing
