Repository allthingslinux/tux, pull requests merged in 2024-03, with the labels that each got.

#76 implement tempvoice
  .env.example
  tux/constants.py
  tux/events/on_voice_state_update.py
Labels: Event

#88 [Infra] stop leaking sentry url
  .env.example
  tux/main.py
Labels: Help Wanted, Meta

#87 [Events] Ghost ping notifier
  tux/cogs/events/message.py
Labels: Event

#89 [Events] add timestamp to ghost ping embed
  tux/cogs/events/message.py
Labels: Event

#91 [Commands] fix ping role permissions
  tux/cogs/utility/ping.py
Labels: Command

#92 added /kick and /ban commands
  tux/cogs/moderation/ban.py
  tux/cogs/moderation/kick.py
Labels: commands

#102 Moderation: Add new commands
  .gitignore
  tux/cogs/admin/load.py
  tux/cogs/admin/reload.py
  tux/cogs/admin/sync.py
  tux/cogs/admin/unload.py
  tux/cogs/moderation/ban.py
  tux/cogs/moderation/kick.py
  tux/cogs/moderation/slowmode.py
  tux/cogs/moderation/unban.py
Labels: commands

#107 Don't count bot mentions as ghost pings
  tux/cogs/utility/ghost_pings.py
Labels: events
