Repository allthingslinux/tux, pull requests merged in 2024-12, with the labels that each got.

#683 Capatalise all queries to wiki
  tux/cogs/utility/wiki.py
Labels: category: commands, priority: low, status: awaiting review

#679 [FIX] fixed bug per issue 678. This allows the bot to retrieve the co…
  tux/cogs/moderation/cases.py
Labels: type: bug

#684 Improve the wiki searching code
  tux/cogs/utility/wiki.py
Labels: category: commands, type: enhancement, priority: medium, status: awaiting review
