Repository allthingslinux/tux, pull requests merged in 2024-09, with the labels that each got.

#510 Add missing argument in editsnippet help
  tux/cogs/utility/snippets.py
Labels: type: bug, category: commands, priority: medium

#511 Fix the CPU and RAM usage in the Ping command
  tux/cogs/utility/ping.py
Labels: type: bug, category: commands

#512 Update guild emoji limit calculation in info cog
  tux/cogs/info/info.py
Labels: type: bug, category: commands

#515 Temp Ban command & Unban Task
  prisma/schema.prisma
  tux/cogs/moderation/tempban.py
  tux/database/controllers/case.py
  tux/database/controllers/guild.py
  tux/utils/flags.py
Labels: category: commands

#518 feat(embeds): Rewrite EmbedCreator
  tux/bot.py
  tux/cogs/admin/eval.py
  tux/cogs/admin/git.py
  tux/cogs/fun/fact.py
  tux/cogs/fun/imgeffect.py
  tux/cogs/fun/random.py
  tux/cogs/fun/xkcd.py
  tux/cogs/guild/config.py
  tux/cogs/guild/export.py
  tux/cogs/guild/rolecount.py
  tux/cogs/info/membercount.py
  tux/cogs/moderation/__init__.py
  tux/cogs/moderation/cases.py
  tux/cogs/services/bookmarks.py
  tux/cogs/services/starboard.py
  tux/cogs/utility/ping.py
  tux/cogs/utility/poll.py
  tux/cogs/utility/query.py
  tux/cogs/utility/remindme.py
  tux/cogs/utility/run.py
  tux/cogs/utility/snippets.py
  tux/cogs/utility/tldr.py
  tux/cogs/utility/wiki.py
  tux/handlers/error.py
  tux/help.py
  tux/main.py
  tux/ui/embeds.py
  tux/ui/modals/report.py
  tux/utils/embeds.py
  tux/utils/exports.py
Labels: status: needs testing, status: awaiting review

#522 Add author to issue body
  tux/cogs/admin/git.py
Labels: category: commands, type: enhancement, priority: medium

#536 Fix report regression & add threads to each report
  tux/ui/modals/report.py
Labels: type: bug, category: commands, priority: critical

#537 feat(starboard.py): Handle all raw reaction events
  tux/cogs/services/starboard.py
Labels: status: awaiting review

#526 Refactor `generate_usage` and use it everywhere
  tux/cogs/admin/dev.py
  tux/cogs/admin/eval.py
  tux/cogs/admin/git.py
  tux/cogs/fun/random.py
  tux/cogs/fun/xkcd.py
  tux/cogs/info/avatar.py
  tux/cogs/info/info.py
  tux/cogs/moderation/cases.py
  tux/cogs/moderation/purge.py
  tux/cogs/moderation/slowmode.py
  tux/cogs/services/starboard.py
  tux/cogs/utility/afk.py
  tux/cogs/utility/ping.py
  tux/cogs/utility/query.py
  tux/cogs/utility/run.py
  tux/cogs/utility/snippets.py
  tux/cogs/utility/timezones.py
  tux/cogs/utility/tldr.py
  tux/cogs/utility/wiki.py
  tux/help.py
  tux/utils/flags.py
Labels: type: enhancement, priority: low, status: awaiting review

#541 Rewrite the `/remindme` command
  prisma/schema.prisma
  tux/cogs/utility/remindme.py
  tux/database/controllers/reminder.py
Labels: status: awaiting review

#567 565 add poll ban
  prisma/schema.prisma
  tux/cogs/moderation/__init__.py
  tux/cogs/moderation/pollban.py
  tux/cogs/moderation/pollunban.py
  tux/cogs/utility/poll.py
  tux/utils/flags.py
Labels: category: commands, type: enhancement, priority: high
