Repository allthingslinux/tux, pull requests merged in 2025-08, with the labels that each got.

#998 fix: replace CheckFailure with PermissionLevelError in SnippetsBaseCog
  tux/cogs/snippets/__init__.py
Labels: category: commands, priority: high

#999 refactor(error): improve command suggestion logic to return better matches using aliases
  tux/handlers/error.py
Labels: category: meta, priority: medium

#1001 build: switch to basedpyright
  .devcontainer/devcontainer.json
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  poetry.lock
  pyproject.toml
  tux/cli/dev.py
Labels: category: meta, priority: medium

#966 feat: migrate from poetry to uv
  .github/CONTRIBUTING.md
  .github/workflows/tests.yml
  DOCKER.md
  Dockerfile
  README.md
  docker-compose.dev.yml
  docker-compose.yml
  docs/content/dev/cli/index.md
  docs/content/dev/coverage.md
  docs/content/dev/database.md
  docs/content/dev/docker_development.md
  docs/content/dev/local_development.md
  poetry.lock
  poetry.toml
  pyproject.toml
  shell.nix
  src/tux/cli/README.md
  src/tux/cli/database.py
  tests/README.md
  uv.lock
Labels: category: meta, priority: low

#1021 fix(moderation): fix ban check
  tux/cogs/moderation/ban.py
Labels: category: commands, priority: high
