Repository allthingslinux/tux, pull requests merged in 2025-05, with the labels that each got.

#851 fix(tldr): condense tldr pages
  tux/cogs/utility/tldr.py
Labels: category: commands, type: enhancement, priority: medium

#855 feat(wolfram): add Wolfram Alpha integration for math/science queries
  .env.example
  tux/cog_loader.py
  tux/cogs/tools/__init__.py
  tux/cogs/tools/wolfram.py
  tux/help.py
  tux/utils/config.py
Labels: category: commands, priority: low

#861 feat(fact): improve fun facts command
  tux/cogs/fun/fact.py
  tux/utils/functions.py
Labels: category: commands, priority: low

#799 feat: Nix Shell
  .gitignore
  flake.lock
  flake.nix
  shell.nix
Labels: category: meta, type: enhancement, priority: medium, misc: good first issue

#864 fix(tty_roles.py): handle role assignment errors
  tux/cogs/services/tty_roles.py
Labels: priority: high

#868 fix(DEVELOPER.md): fix broken cli usage link
  DEVELOPER.md
Labels: type: bug
